// Auto-generated. 244 palettes.
pub const Entry = struct { name: []const u8, bytes: []const u8 };
pub const entries = [_]Entry{
    .{ .name = "3024", .bytes = @embedFile("../palettes/3024.palette") },
    .{ .name = "Aci", .bytes = @embedFile("../palettes/Aci.palette") },
    .{ .name = "Aco", .bytes = @embedFile("../palettes/Aco.palette") },
    .{ .name = "Adventure Time", .bytes = @embedFile("../palettes/Adventure Time.palette") },
    .{ .name = "Afterglow", .bytes = @embedFile("../palettes/Afterglow.palette") },
    .{ .name = "Alien Blood", .bytes = @embedFile("../palettes/Alien Blood.palette") },
    .{ .name = "Apprentice", .bytes = @embedFile("../palettes/Apprentice.palette") },
    .{ .name = "Argonaut", .bytes = @embedFile("../palettes/Argonaut.palette") },
    .{ .name = "Arthur", .bytes = @embedFile("../palettes/Arthur.palette") },
    .{ .name = "Atom", .bytes = @embedFile("../palettes/Atom.palette") },
    .{ .name = "Aura", .bytes = @embedFile("../palettes/Aura.palette") },
    .{ .name = "Ayu Mirage", .bytes = @embedFile("../palettes/Ayu Mirage.palette") },
    .{ .name = "Ayu", .bytes = @embedFile("../palettes/Ayu.palette") },
    .{ .name = "Azu", .bytes = @embedFile("../palettes/Azu.palette") },
    .{ .name = "Belafonte", .bytes = @embedFile("../palettes/Belafonte.palette") },
    .{ .name = "Bim", .bytes = @embedFile("../palettes/Bim.palette") },
    .{ .name = "Birds Of Paradise", .bytes = @embedFile("../palettes/Birds Of Paradise.palette") },
    .{ .name = "Blazer", .bytes = @embedFile("../palettes/Blazer.palette") },
    .{ .name = "Bluloco Light", .bytes = @embedFile("../palettes/Bluloco Light.palette") },
    .{ .name = "Bluloco Zsh Light", .bytes = @embedFile("../palettes/Bluloco Zsh Light.palette") },
    .{ .name = "Borland", .bytes = @embedFile("../palettes/Borland.palette") },
    .{ .name = "Breath Silverfox", .bytes = @embedFile("../palettes/Breath Silverfox.palette") },
    .{ .name = "Breath", .bytes = @embedFile("../palettes/Breath.palette") },
    .{ .name = "Breeze", .bytes = @embedFile("../palettes/Breeze.palette") },
    .{ .name = "Broadcast", .bytes = @embedFile("../palettes/Broadcast.palette") },
    .{ .name = "Brogrammer", .bytes = @embedFile("../palettes/Brogrammer.palette") },
    .{ .name = "C64", .bytes = @embedFile("../palettes/C64.palette") },
    .{ .name = "Cai", .bytes = @embedFile("../palettes/Cai.palette") },
    .{ .name = "Catppuccin Frappé", .bytes = @embedFile("../palettes/Catppuccin Frappé.palette") },
    .{ .name = "Catppuccin Latte", .bytes = @embedFile("../palettes/Catppuccin Latte.palette") },
    .{ .name = "Catppuccin Macchiato", .bytes = @embedFile("../palettes/Catppuccin Macchiato.palette") },
    .{ .name = "Catppuccin Mocha", .bytes = @embedFile("../palettes/Catppuccin Mocha.palette") },
    .{ .name = "Chalk", .bytes = @embedFile("../palettes/Chalk.palette") },
    .{ .name = "Chalkboard", .bytes = @embedFile("../palettes/Chalkboard.palette") },
    .{ .name = "Chameleon", .bytes = @embedFile("../palettes/Chameleon.palette") },
    .{ .name = "Ciapre", .bytes = @embedFile("../palettes/Ciapre.palette") },
    .{ .name = "Clrs", .bytes = @embedFile("../palettes/Clrs.palette") },
    .{ .name = "Cobalt 2", .bytes = @embedFile("../palettes/Cobalt 2.palette") },
    .{ .name = "Cobalt Neon", .bytes = @embedFile("../palettes/Cobalt Neon.palette") },
    .{ .name = "Colorcli", .bytes = @embedFile("../palettes/Colorcli.palette") },
    .{ .name = "Crayon Pony Fish", .bytes = @embedFile("../palettes/Crayon Pony Fish.palette") },
    .{ .name = "Dark Pastel", .bytes = @embedFile("../palettes/Dark Pastel.palette") },
    .{ .name = "Darkside", .bytes = @embedFile("../palettes/Darkside.palette") },
    .{ .name = "Dehydration", .bytes = @embedFile("../palettes/Dehydration.palette") },
    .{ .name = "Desert", .bytes = @embedFile("../palettes/Desert.palette") },
    .{ .name = "Dimmed Monokai", .bytes = @embedFile("../palettes/Dimmed Monokai.palette") },
    .{ .name = "Dissonance", .bytes = @embedFile("../palettes/Dissonance.palette") },
    .{ .name = "Earthsong", .bytes = @embedFile("../palettes/Earthsong.palette") },
    .{ .name = "Elemental", .bytes = @embedFile("../palettes/Elemental.palette") },
    .{ .name = "Elementary", .bytes = @embedFile("../palettes/Elementary.palette") },
    .{ .name = "Elic", .bytes = @embedFile("../palettes/Elic.palette") },
    .{ .name = "Elio", .bytes = @embedFile("../palettes/Elio.palette") },
    .{ .name = "Espresso Libre", .bytes = @embedFile("../palettes/Espresso Libre.palette") },
    .{ .name = "Espresso", .bytes = @embedFile("../palettes/Espresso.palette") },
    .{ .name = "Everblush", .bytes = @embedFile("../palettes/Everblush.palette") },
    .{ .name = "Everforest", .bytes = @embedFile("../palettes/Everforest.palette") },
    .{ .name = "Fairy Floss Dark", .bytes = @embedFile("../palettes/Fairy Floss Dark.palette") },
    .{ .name = "Fairy Floss", .bytes = @embedFile("../palettes/Fairy Floss.palette") },
    .{ .name = "Fishtank", .bytes = @embedFile("../palettes/Fishtank.palette") },
    .{ .name = "Flat Remix", .bytes = @embedFile("../palettes/Flat Remix.palette") },
    .{ .name = "Flat", .bytes = @embedFile("../palettes/Flat.palette") },
    .{ .name = "Flatland", .bytes = @embedFile("../palettes/Flatland.palette") },
    .{ .name = "Foxnightly", .bytes = @embedFile("../palettes/Foxnightly.palette") },
    .{ .name = "Freya", .bytes = @embedFile("../palettes/Freya.palette") },
    .{ .name = "Frontend Delight", .bytes = @embedFile("../palettes/Frontend Delight.palette") },
    .{ .name = "Frontend Fun Forrest", .bytes = @embedFile("../palettes/Frontend Fun Forrest.palette") },
    .{ .name = "Frontend Galaxy", .bytes = @embedFile("../palettes/Frontend Galaxy.palette") },
    .{ .name = "GNOME Legacy", .bytes = @embedFile("../palettes/GNOME Legacy.palette") },
    .{ .name = "Geohot", .bytes = @embedFile("../palettes/Geohot.palette") },
    .{ .name = "Github", .bytes = @embedFile("../palettes/Github.palette") },
    .{ .name = "Gogh", .bytes = @embedFile("../palettes/Gogh.palette") },
    .{ .name = "Gooey", .bytes = @embedFile("../palettes/Gooey.palette") },
    .{ .name = "Google", .bytes = @embedFile("../palettes/Google.palette") },
    .{ .name = "Gotham", .bytes = @embedFile("../palettes/Gotham.palette") },
    .{ .name = "Grape", .bytes = @embedFile("../palettes/Grape.palette") },
    .{ .name = "Grass", .bytes = @embedFile("../palettes/Grass.palette") },
    .{ .name = "Gruvbox Material", .bytes = @embedFile("../palettes/Gruvbox Material.palette") },
    .{ .name = "Gruvbox", .bytes = @embedFile("../palettes/Gruvbox.palette") },
    .{ .name = "Hardcore", .bytes = @embedFile("../palettes/Hardcore.palette") },
    .{ .name = "Harper", .bytes = @embedFile("../palettes/Harper.palette") },
    .{ .name = "Hemisu", .bytes = @embedFile("../palettes/Hemisu.palette") },
    .{ .name = "Highway", .bytes = @embedFile("../palettes/Highway.palette") },
    .{ .name = "Hipster Green", .bytes = @embedFile("../palettes/Hipster Green.palette") },
    .{ .name = "Homebrew Light", .bytes = @embedFile("../palettes/Homebrew Light.palette") },
    .{ .name = "Homebrew Ocean", .bytes = @embedFile("../palettes/Homebrew Ocean.palette") },
    .{ .name = "Homebrew", .bytes = @embedFile("../palettes/Homebrew.palette") },
    .{ .name = "Horizon", .bytes = @embedFile("../palettes/Horizon.palette") },
    .{ .name = "Hurtado", .bytes = @embedFile("../palettes/Hurtado.palette") },
    .{ .name = "Hybrid", .bytes = @embedFile("../palettes/Hybrid.palette") },
    .{ .name = "Ibm 3270 (High Contrast)", .bytes = @embedFile("../palettes/Ibm 3270 (High Contrast).palette") },
    .{ .name = "Ibm3270", .bytes = @embedFile("../palettes/Ibm3270.palette") },
    .{ .name = "Ic Green Ppl", .bytes = @embedFile("../palettes/Ic Green Ppl.palette") },
    .{ .name = "Ic Orange Ppl", .bytes = @embedFile("../palettes/Ic Orange Ppl.palette") },
    .{ .name = "Idle Toes", .bytes = @embedFile("../palettes/Idle Toes.palette") },
    .{ .name = "Ir Black", .bytes = @embedFile("../palettes/Ir Black.palette") },
    .{ .name = "Jackie Brown", .bytes = @embedFile("../palettes/Jackie Brown.palette") },
    .{ .name = "Japanesque", .bytes = @embedFile("../palettes/Japanesque.palette") },
    .{ .name = "Jellybeans", .bytes = @embedFile("../palettes/Jellybeans.palette") },
    .{ .name = "Jup", .bytes = @embedFile("../palettes/Jup.palette") },
    .{ .name = "Kanagawa", .bytes = @embedFile("../palettes/Kanagawa.palette") },
    .{ .name = "Kibble", .bytes = @embedFile("../palettes/Kibble.palette") },
    .{ .name = "Kokuban", .bytes = @embedFile("../palettes/Kokuban.palette") },
    .{ .name = "Laserwave", .bytes = @embedFile("../palettes/Laserwave.palette") },
    .{ .name = "Later This Evening", .bytes = @embedFile("../palettes/Later This Evening.palette") },
    .{ .name = "Lavandula", .bytes = @embedFile("../palettes/Lavandula.palette") },
    .{ .name = "Liquid Carbon Transparent", .bytes = @embedFile("../palettes/Liquid Carbon Transparent.palette") },
    .{ .name = "Liquid Carbon", .bytes = @embedFile("../palettes/Liquid Carbon.palette") },
    .{ .name = "Lunaria Eclipse", .bytes = @embedFile("../palettes/Lunaria Eclipse.palette") },
    .{ .name = "Lunaria", .bytes = @embedFile("../palettes/Lunaria.palette") },
    .{ .name = "Maia", .bytes = @embedFile("../palettes/Maia.palette") },
    .{ .name = "Man Page", .bytes = @embedFile("../palettes/Man Page.palette") },
    .{ .name = "Mar", .bytes = @embedFile("../palettes/Mar.palette") },
    .{ .name = "Material", .bytes = @embedFile("../palettes/Material.palette") },
    .{ .name = "Mathias", .bytes = @embedFile("../palettes/Mathias.palette") },
    .{ .name = "Medallion", .bytes = @embedFile("../palettes/Medallion.palette") },
    .{ .name = "Misterioso", .bytes = @embedFile("../palettes/Misterioso.palette") },
    .{ .name = "Molokai", .bytes = @embedFile("../palettes/Molokai.palette") },
    .{ .name = "Mona Lisa", .bytes = @embedFile("../palettes/Mona Lisa.palette") },
    .{ .name = "Mono Amber", .bytes = @embedFile("../palettes/Mono Amber.palette") },
    .{ .name = "Mono Cyan", .bytes = @embedFile("../palettes/Mono Cyan.palette") },
    .{ .name = "Mono Green", .bytes = @embedFile("../palettes/Mono Green.palette") },
    .{ .name = "Mono Red", .bytes = @embedFile("../palettes/Mono Red.palette") },
    .{ .name = "Mono White", .bytes = @embedFile("../palettes/Mono White.palette") },
    .{ .name = "Mono Yellow", .bytes = @embedFile("../palettes/Mono Yellow.palette") },
    .{ .name = "Monokai Dark", .bytes = @embedFile("../palettes/Monokai Dark.palette") },
    .{ .name = "Monokai Pro Ristretto", .bytes = @embedFile("../palettes/Monokai Pro Ristretto.palette") },
    .{ .name = "Monokai Pro", .bytes = @embedFile("../palettes/Monokai Pro.palette") },
    .{ .name = "Monokai Soda", .bytes = @embedFile("../palettes/Monokai Soda.palette") },
    .{ .name = "Moonfly", .bytes = @embedFile("../palettes/Moonfly.palette") },
    .{ .name = "Morada", .bytes = @embedFile("../palettes/Morada.palette") },
    .{ .name = "N0Tch2K", .bytes = @embedFile("../palettes/N0Tch2K.palette") },
    .{ .name = "Neon Night", .bytes = @embedFile("../palettes/Neon Night.palette") },
    .{ .name = "Neopolitan", .bytes = @embedFile("../palettes/Neopolitan.palette") },
    .{ .name = "Nep", .bytes = @embedFile("../palettes/Nep.palette") },
    .{ .name = "Neutron", .bytes = @embedFile("../palettes/Neutron.palette") },
    .{ .name = "Night Owl", .bytes = @embedFile("../palettes/Night Owl.palette") },
    .{ .name = "Nightfly", .bytes = @embedFile("../palettes/Nightfly.palette") },
    .{ .name = "Nightlion V1", .bytes = @embedFile("../palettes/Nightlion V1.palette") },
    .{ .name = "Nightlion V2", .bytes = @embedFile("../palettes/Nightlion V2.palette") },
    .{ .name = "Nighty", .bytes = @embedFile("../palettes/Nighty.palette") },
    .{ .name = "Novel", .bytes = @embedFile("../palettes/Novel.palette") },
    .{ .name = "Obsidian", .bytes = @embedFile("../palettes/Obsidian.palette") },
    .{ .name = "Ocean Dark", .bytes = @embedFile("../palettes/Ocean Dark.palette") },
    .{ .name = "Oceanic Next", .bytes = @embedFile("../palettes/Oceanic Next.palette") },
    .{ .name = "Ollie", .bytes = @embedFile("../palettes/Ollie.palette") },
    .{ .name = "Omni", .bytes = @embedFile("../palettes/Omni.palette") },
    .{ .name = "One Half Black", .bytes = @embedFile("../palettes/One Half Black.palette") },
    .{ .name = "One", .bytes = @embedFile("../palettes/One.palette") },
    .{ .name = "Oxocarbon Dark", .bytes = @embedFile("../palettes/Oxocarbon Dark.palette") },
    .{ .name = "Palenight", .bytes = @embedFile("../palettes/Palenight.palette") },
    .{ .name = "Pali", .bytes = @embedFile("../palettes/Pali.palette") },
    .{ .name = "Panda", .bytes = @embedFile("../palettes/Panda.palette") },
    .{ .name = "Papercolor", .bytes = @embedFile("../palettes/Papercolor.palette") },
    .{ .name = "Paraiso Dark", .bytes = @embedFile("../palettes/Paraiso Dark.palette") },
    .{ .name = "Paul Millr", .bytes = @embedFile("../palettes/Paul Millr.palette") },
    .{ .name = "Pencil", .bytes = @embedFile("../palettes/Pencil.palette") },
    .{ .name = "Peppermint", .bytes = @embedFile("../palettes/Peppermint.palette") },
    .{ .name = "Pixiefloss", .bytes = @embedFile("../palettes/Pixiefloss.palette") },
    .{ .name = "Pnevma", .bytes = @embedFile("../palettes/Pnevma.palette") },
    .{ .name = "Powershell", .bytes = @embedFile("../palettes/Powershell.palette") },
    .{ .name = "Predawn", .bytes = @embedFile("../palettes/Predawn.palette") },
    .{ .name = "Pro", .bytes = @embedFile("../palettes/Pro.palette") },
    .{ .name = "Purple People Eater", .bytes = @embedFile("../palettes/Purple People Eater.palette") },
    .{ .name = "Red Alert", .bytes = @embedFile("../palettes/Red Alert.palette") },
    .{ .name = "Red Sands", .bytes = @embedFile("../palettes/Red Sands.palette") },
    .{ .name = "Relaxed", .bytes = @embedFile("../palettes/Relaxed.palette") },
    .{ .name = "Rippedcasts", .bytes = @embedFile("../palettes/Rippedcasts.palette") },
    .{ .name = "Rosé Pine Dawn", .bytes = @embedFile("../palettes/Rosé Pine Dawn.palette") },
    .{ .name = "Rosé Pine Moon", .bytes = @embedFile("../palettes/Rosé Pine Moon.palette") },
    .{ .name = "Rosé Pine", .bytes = @embedFile("../palettes/Rosé Pine.palette") },
    .{ .name = "Royal", .bytes = @embedFile("../palettes/Royal.palette") },
    .{ .name = "Sat", .bytes = @embedFile("../palettes/Sat.palette") },
    .{ .name = "Sea Shells", .bytes = @embedFile("../palettes/Sea Shells.palette") },
    .{ .name = "Seafoam Pastel", .bytes = @embedFile("../palettes/Seafoam Pastel.palette") },
    .{ .name = "Selenized", .bytes = @embedFile("../palettes/Selenized.palette") },
    .{ .name = "Seti", .bytes = @embedFile("../palettes/Seti.palette") },
    .{ .name = "Shaman", .bytes = @embedFile("../palettes/Shaman.palette") },
    .{ .name = "Shel", .bytes = @embedFile("../palettes/Shel.palette") },
    .{ .name = "Slate", .bytes = @embedFile("../palettes/Slate.palette") },
    .{ .name = "Smyck", .bytes = @embedFile("../palettes/Smyck.palette") },
    .{ .name = "Snazzy", .bytes = @embedFile("../palettes/Snazzy.palette") },
    .{ .name = "Soft Server", .bytes = @embedFile("../palettes/Soft Server.palette") },
    .{ .name = "Solarized Darcula", .bytes = @embedFile("../palettes/Solarized Darcula.palette") },
    .{ .name = "Solarized Dark Higher Contrast", .bytes = @embedFile("../palettes/Solarized Dark Higher Contrast.palette") },
    .{ .name = "Solarized", .bytes = @embedFile("../palettes/Solarized.palette") },
    .{ .name = "Sonokai", .bytes = @embedFile("../palettes/Sonokai.palette") },
    .{ .name = "Spacedust", .bytes = @embedFile("../palettes/Spacedust.palette") },
    .{ .name = "Spacegray Eighties Dull", .bytes = @embedFile("../palettes/Spacegray Eighties Dull.palette") },
    .{ .name = "Spacegray Eighties", .bytes = @embedFile("../palettes/Spacegray Eighties.palette") },
    .{ .name = "Spacegray", .bytes = @embedFile("../palettes/Spacegray.palette") },
    .{ .name = "Spring", .bytes = @embedFile("../palettes/Spring.palette") },
    .{ .name = "Square", .bytes = @embedFile("../palettes/Square.palette") },
    .{ .name = "Srcery", .bytes = @embedFile("../palettes/Srcery.palette") },
    .{ .name = "Summer Pop", .bytes = @embedFile("../palettes/Summer Pop.palette") },
    .{ .name = "Sundried", .bytes = @embedFile("../palettes/Sundried.palette") },
    .{ .name = "Sweet Eliverlara", .bytes = @embedFile("../palettes/Sweet Eliverlara.palette") },
    .{ .name = "Sweet Terminal", .bytes = @embedFile("../palettes/Sweet Terminal.palette") },
    .{ .name = "Symphonic", .bytes = @embedFile("../palettes/Symphonic.palette") },
    .{ .name = "Synthwave Alpha", .bytes = @embedFile("../palettes/Synthwave Alpha.palette") },
    .{ .name = "Synthwave", .bytes = @embedFile("../palettes/Synthwave.palette") },
    .{ .name = "Teerb", .bytes = @embedFile("../palettes/Teerb.palette") },
    .{ .name = "Tender", .bytes = @embedFile("../palettes/Tender.palette") },
    .{ .name = "Terminal Basic", .bytes = @embedFile("../palettes/Terminal Basic.palette") },
    .{ .name = "Terminix Dark", .bytes = @embedFile("../palettes/Terminix Dark.palette") },
    .{ .name = "Thayer Bright", .bytes = @embedFile("../palettes/Thayer Bright.palette") },
    .{ .name = "Tin", .bytes = @embedFile("../palettes/Tin.palette") },
    .{ .name = "Tokyo Night Day", .bytes = @embedFile("../palettes/Tokyo Night Day.palette") },
    .{ .name = "Tokyo Night Light", .bytes = @embedFile("../palettes/Tokyo Night Light.palette") },
    .{ .name = "Tokyo Night Moon", .bytes = @embedFile("../palettes/Tokyo Night Moon.palette") },
    .{ .name = "Tokyo Night Storm", .bytes = @embedFile("../palettes/Tokyo Night Storm.palette") },
    .{ .name = "Tokyo Night", .bytes = @embedFile("../palettes/Tokyo Night.palette") },
    .{ .name = "Tomorrow Night Blue", .bytes = @embedFile("../palettes/Tomorrow Night Blue.palette") },
    .{ .name = "Tomorrow Night Bright", .bytes = @embedFile("../palettes/Tomorrow Night Bright.palette") },
    .{ .name = "Tomorrow Night Eighties", .bytes = @embedFile("../palettes/Tomorrow Night Eighties.palette") },
    .{ .name = "Tomorrow Night", .bytes = @embedFile("../palettes/Tomorrow Night.palette") },
    .{ .name = "Tomorrow", .bytes = @embedFile("../palettes/Tomorrow.palette") },
    .{ .name = "Toy Chest", .bytes = @embedFile("../palettes/Toy Chest.palette") },
    .{ .name = "Treehouse", .bytes = @embedFile("../palettes/Treehouse.palette") },
    .{ .name = "Twilight", .bytes = @embedFile("../palettes/Twilight.palette") },
    .{ .name = "Ubuntu", .bytes = @embedFile("../palettes/Ubuntu.palette") },
    .{ .name = "Ura", .bytes = @embedFile("../palettes/Ura.palette") },
    .{ .name = "Urple", .bytes = @embedFile("../palettes/Urple.palette") },
    .{ .name = "Vag", .bytes = @embedFile("../palettes/Vag.palette") },
    .{ .name = "Vaughn", .bytes = @embedFile("../palettes/Vaughn.palette") },
    .{ .name = "Vibrant Ink", .bytes = @embedFile("../palettes/Vibrant Ink.palette") },
    .{ .name = "Vs Code", .bytes = @embedFile("../palettes/Vs Code.palette") },
    .{ .name = "Warm Neon", .bytes = @embedFile("../palettes/Warm Neon.palette") },
    .{ .name = "Website", .bytes = @embedFile("../palettes/Website.palette") },
    .{ .name = "Wez", .bytes = @embedFile("../palettes/Wez.palette") },
    .{ .name = "Wild Cherry", .bytes = @embedFile("../palettes/Wild Cherry.palette") },
    .{ .name = "Wombat", .bytes = @embedFile("../palettes/Wombat.palette") },
    .{ .name = "Wryan", .bytes = @embedFile("../palettes/Wryan.palette") },
    .{ .name = "Wzoreck", .bytes = @embedFile("../palettes/Wzoreck.palette") },
    .{ .name = "Zenburn", .bytes = @embedFile("../palettes/Zenburn.palette") },
    .{ .name = "campbell", .bytes = @embedFile("../palettes/campbell.palette") },
    .{ .name = "dracula", .bytes = @embedFile("../palettes/dracula.palette") },
    .{ .name = "gnome-high-contrast", .bytes = @embedFile("../palettes/gnome-high-contrast.palette") },
    .{ .name = "gnome", .bytes = @embedFile("../palettes/gnome.palette") },
    .{ .name = "linux", .bytes = @embedFile("../palettes/linux.palette") },
    .{ .name = "nord", .bytes = @embedFile("../palettes/nord.palette") },
    .{ .name = "rxvt", .bytes = @embedFile("../palettes/rxvt.palette") },
    .{ .name = "solarized", .bytes = @embedFile("../palettes/solarized.palette") },
    .{ .name = "tango", .bytes = @embedFile("../palettes/tango.palette") },
    .{ .name = "xterm", .bytes = @embedFile("../palettes/xterm.palette") },
};
